import { Link } from "@chakra-ui/next-js";
import { Text, VStack } from "@chakra-ui/react";
import { Inter } from "next/font/google";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export default function Twitter() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main>
        <VStack spacing={5} mt={150}>
          <Text fontSize='4xl'>Co:Create Social Integrations Demo</Text>
          <Link href='/twitter'>
            <Text color='blue' fontSize='2xl' as='u'>
              Twitter
            </Text>
          </Link>
          <Link href='/instagram'>
            <Text color='blue' fontSize='2xl' as='u'>
              Instagram
            </Text>
          </Link>
          <Link href='/tiktok'>
            <Text color='blue' fontSize='2xl' as='u'>
              TikTok
            </Text>
          </Link>
        </VStack>
      </main>
    </>
  );
}
